version: '3.8'

services:
  app:
    image: hanhnguyen312/be-crud-vote-users
    container_name: nodejs-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    # db chay truoc 
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: lacxinhh
      MYSQL_DATABASE: s_usermnmt
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge